version: "3.8"
services:

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: dockerfiles/php/Dockerfile
    volumes:
      - "./:/app"

  db:
    container_name: db
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - 5432:5432

volumes:
  dbdata: